version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    expose:
      - "5000" 

  nginx:
    build: ./nginx
    ports:
      - "8080:80"  
    depends_on:
      - app