name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Nginx configuration
      run: |
        docker-compose config
        docker-compose build
        docker-compose up -d
        curl --retry 5 --retry-delay 5 http://localhost:8080 | grep "Hello, World!"
        
    - name: Run static code analysis with Pylint
      run: |
        pylint src/ --exit-zero --output-format=json:pylint-report.json || true
        
    - name: Upload Pylint report
      uses: actions/upload-artifact@v4
      with:
        name: pylint-report
        path: pylint-report.json
        
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=src --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3